/*
Copyright 2019 the original author or authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	"time"

	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"

	v1alpha1 "github.com/projectriff/system/pkg/apis/bindings/v1alpha1"
	scheme "github.com/projectriff/system/pkg/client/clientset/versioned/scheme"
)

// ImageBindingsGetter has a method to return a ImageBindingInterface.
// A group's client should implement this interface.
type ImageBindingsGetter interface {
	ImageBindings(namespace string) ImageBindingInterface
}

// ImageBindingInterface has methods to work with ImageBinding resources.
type ImageBindingInterface interface {
	Create(*v1alpha1.ImageBinding) (*v1alpha1.ImageBinding, error)
	Update(*v1alpha1.ImageBinding) (*v1alpha1.ImageBinding, error)
	UpdateStatus(*v1alpha1.ImageBinding) (*v1alpha1.ImageBinding, error)
	Delete(name string, options *v1.DeleteOptions) error
	DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error
	Get(name string, options v1.GetOptions) (*v1alpha1.ImageBinding, error)
	List(opts v1.ListOptions) (*v1alpha1.ImageBindingList, error)
	Watch(opts v1.ListOptions) (watch.Interface, error)
	Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1alpha1.ImageBinding, err error)
	ImageBindingExpansion
}

// imageBindings implements ImageBindingInterface
type imageBindings struct {
	client rest.Interface
	ns     string
}

// newImageBindings returns a ImageBindings
func newImageBindings(c *BindingsV1alpha1Client, namespace string) *imageBindings {
	return &imageBindings{
		client: c.RESTClient(),
		ns:     namespace,
	}
}

// Get takes name of the imageBinding, and returns the corresponding imageBinding object, and an error if there is any.
func (c *imageBindings) Get(name string, options v1.GetOptions) (result *v1alpha1.ImageBinding, err error) {
	result = &v1alpha1.ImageBinding{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("imagebindings").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do().
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of ImageBindings that match those selectors.
func (c *imageBindings) List(opts v1.ListOptions) (result *v1alpha1.ImageBindingList, err error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	result = &v1alpha1.ImageBindingList{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("imagebindings").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Do().
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested imageBindings.
func (c *imageBindings) Watch(opts v1.ListOptions) (watch.Interface, error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	opts.Watch = true
	return c.client.Get().
		Namespace(c.ns).
		Resource("imagebindings").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Watch()
}

// Create takes the representation of a imageBinding and creates it.  Returns the server's representation of the imageBinding, and an error, if there is any.
func (c *imageBindings) Create(imageBinding *v1alpha1.ImageBinding) (result *v1alpha1.ImageBinding, err error) {
	result = &v1alpha1.ImageBinding{}
	err = c.client.Post().
		Namespace(c.ns).
		Resource("imagebindings").
		Body(imageBinding).
		Do().
		Into(result)
	return
}

// Update takes the representation of a imageBinding and updates it. Returns the server's representation of the imageBinding, and an error, if there is any.
func (c *imageBindings) Update(imageBinding *v1alpha1.ImageBinding) (result *v1alpha1.ImageBinding, err error) {
	result = &v1alpha1.ImageBinding{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("imagebindings").
		Name(imageBinding.Name).
		Body(imageBinding).
		Do().
		Into(result)
	return
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().

func (c *imageBindings) UpdateStatus(imageBinding *v1alpha1.ImageBinding) (result *v1alpha1.ImageBinding, err error) {
	result = &v1alpha1.ImageBinding{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("imagebindings").
		Name(imageBinding.Name).
		SubResource("status").
		Body(imageBinding).
		Do().
		Into(result)
	return
}

// Delete takes name of the imageBinding and deletes it. Returns an error if one occurs.
func (c *imageBindings) Delete(name string, options *v1.DeleteOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("imagebindings").
		Name(name).
		Body(options).
		Do().
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *imageBindings) DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error {
	var timeout time.Duration
	if listOptions.TimeoutSeconds != nil {
		timeout = time.Duration(*listOptions.TimeoutSeconds) * time.Second
	}
	return c.client.Delete().
		Namespace(c.ns).
		Resource("imagebindings").
		VersionedParams(&listOptions, scheme.ParameterCodec).
		Timeout(timeout).
		Body(options).
		Do().
		Error()
}

// Patch applies the patch and returns the patched imageBinding.
func (c *imageBindings) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1alpha1.ImageBinding, err error) {
	result = &v1alpha1.ImageBinding{}
	err = c.client.Patch(pt).
		Namespace(c.ns).
		Resource("imagebindings").
		SubResource(subresources...).
		Name(name).
		Body(data).
		Do().
		Into(result)
	return
}
