
---
apiVersion: admissionregistration.k8s.io/v1beta1
kind: MutatingWebhookConfiguration
metadata:
  creationTimestamp: null
  name: mutating-webhook-configuration
webhooks:
- clientConfig:
    caBundle: Cg==
    service:
      name: webhook-service
      namespace: system
      path: /mutate-streaming-projectriff-io-v1alpha1-kafkaprovider
  failurePolicy: Fail
  name: kafkaproviders.streaming.projectriff.io
  rules:
  - apiGroups:
    - streaming.projectriff.io
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - kafkaproviders
- clientConfig:
    caBundle: Cg==
    service:
      name: webhook-service
      namespace: system
      path: /mutate-streaming-projectriff-io-v1alpha1-processor
  failurePolicy: Fail
  name: processors.streaming.projectriff.io
  rules:
  - apiGroups:
    - streaming.projectriff.io
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - processors
- clientConfig:
    caBundle: Cg==
    service:
      name: webhook-service
      namespace: system
      path: /mutate-streaming-projectriff-io-v1alpha1-pulsarprovider
  failurePolicy: Fail
  name: pulsarproviders.streaming.projectriff.io
  rules:
  - apiGroups:
    - streaming.projectriff.io
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - pulsarproviders
- clientConfig:
    caBundle: Cg==
    service:
      name: webhook-service
      namespace: system
      path: /mutate-streaming-projectriff-io-v1alpha1-stream
  failurePolicy: Fail
  name: streams.streaming.projectriff.io
  rules:
  - apiGroups:
    - streaming.projectriff.io
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - streams

---
apiVersion: admissionregistration.k8s.io/v1beta1
kind: ValidatingWebhookConfiguration
metadata:
  creationTimestamp: null
  name: validating-webhook-configuration
webhooks:
- clientConfig:
    caBundle: Cg==
    service:
      name: webhook-service
      namespace: system
      path: /validate-streaming-projectriff-io-v1alpha1-kafkaprovider
  failurePolicy: Fail
  name: kafkaproviders.streaming.projectriff.io
  rules:
  - apiGroups:
    - streaming.projectriff.io
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - kafkaproviders
- clientConfig:
    caBundle: Cg==
    service:
      name: webhook-service
      namespace: system
      path: /validate-streaming-projectriff-io-v1alpha1-processor
  failurePolicy: Fail
  name: processors.streaming.projectriff.io
  rules:
  - apiGroups:
    - streaming.projectriff.io
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - processors
- clientConfig:
    caBundle: Cg==
    service:
      name: webhook-service
      namespace: system
      path: /validate-streaming-projectriff-io-v1alpha1-pulsarprovider
  failurePolicy: Fail
  name: pulsarproviders.streaming.projectriff.io
  rules:
  - apiGroups:
    - streaming.projectriff.io
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - pulsarproviders
- clientConfig:
    caBundle: Cg==
    service:
      name: webhook-service
      namespace: system
      path: /validate-streaming-projectriff-io-v1alpha1-stream
  failurePolicy: Fail
  name: streams.streaming.projectriff.io
  rules:
  - apiGroups:
    - streaming.projectriff.io
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - streams
